<div style="margin: 4em">
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;"><strong>CONDICIONES DE USO</strong></p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;"><br><br></p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;"><strong>1.- Introducci&oacute;n</strong></p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Te damos la bienvenida al sitio web <u><a href="http://www.inmozon.com/">www.inmozon.com</a>.&nbsp;</u><span style="text-decoration: none;">Los productos y servicios del portal se proporcionan a trav&eacute;s de la mercantil Inmoarea Partners, SL. En adelante Inmozon.</span></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">El uso de nuestro Portal implica la aceptaci&oacute;n y adhesi&oacute;n a todas nuestras Condiciones de Uso y a nuestra Pol&iacute;tica de Privacidad. Te recomendamos que las leas detenidamente.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;"><span style="text-decoration: none;">&nbsp;<strong>2.- Definici&oacute;n del servicio de inmozon.com</strong></span></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">El Servicio de Inmozon consiste en la inserci&oacute;n, por parte de los propietarios (usuarios en adelante) de viviendas, de toda la informaci&oacute;n necesaria para la venta de dicha vivienda por parte de las Inmobiliarias suscritas a Inmozon y que forman parte de nuestra red.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Tanto Inmozon como sus Inmobiliarias suscritas a su portal, se reservan el derecho a difundir en terceros portales, total o parcialmente, las viviendas del usuario, as&iacute; como en otros sitios web, tales como redes sociales o blogs, aceptando el Propietario dicha condici&oacute;n.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Para insertar viviendas en el Portal, el usuario ha de completar el formulario de &quot;Publicar Casa&quot;. El propietario acceder&aacute; a la plataforma y se registrar&aacute; introduciendo la informaci&oacute;n requerida por INMOZON en dicho momento.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Para poder completar el registro en Inmozon, La Propiedad deber&aacute; facilitar la siguiente documentaci&oacute;n:</p>
<ul>
    <li>
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">T&iacute;tulo de propiedad de la finca anteriormente descrita. Escritura de compra venta o Nota Simple. Podr&aacute; omitir datos no necesarios para la verificaci&oacute;n de la titularidad (como por ejemplo precio de adquisici&oacute;n o anterior titular).</p>
    </li>
    <li>
        <!-- <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Ultimo recibo IBI</p> -->
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Documentos de identidad. DNI, Pasaporte, NIE.</p>
    </li>
    <li>
        <!-- <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Ultima factura de suministros de agua, luz o gas</p> -->
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Contrato de Mediación Firmado (facilitado por Inmozon)</p>
    </li>
    <li>
        <!-- <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Administrador de fincas. Nombre, domicilio, email y tel&eacute;fono</p> -->
        <p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Información adicional (Opcional) tal como último recibo del Ibi o facturas de suministros</p>
    </li>
</ul>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Una vez validada la documentaci&oacute;n por Inmozon, la finca ser&aacute; incluida en la plataforma y estar&aacute; visible y a disposici&oacute;n de todos sus usuarios profesionales.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Una vez completado el registro, podr&aacute; acceder a su perfil para editar el mismo.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">El usuario recibe una clave de acceso en el momento del alta. Con el correo electr&oacute;nico que ha facilitado el anunciante en la inserci&oacute;n del anuncio y la clave de acceso, el anunciante puede acceder al &aacute;rea &quot;Modificar mis Anuncios&quot; para modificar, renovar o eliminar sus anuncios y consultar los mensajes que han llegado por parte de nuestra red de inmobiliarias como respuesta al anuncio en forma de correo electr&oacute;nico.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;"><br><br></p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">LA PROPIEDAD podr&aacute; darse de baja de la plataforma comunic&aacute;ndolo mediante correo electr&oacute;nico a trav&eacute;s de la direcci&oacute;n <u><a href="mailto:info@inmozon.com">info@inmozon.com</a></u></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><strong>3.- Uso del portal y sus servicios</strong></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">El usuario se compromete a utilizar el Portal, sus contenidos y servicios conforme con:</p>
<ol>
    <li>
        <p style="text-align: justify;background: transparent;margin-top: 0.21cm;margin-bottom: 0.21cm;line-height: 0.42cm;">La Ley o cualesquiera otras normas del ordenamiento jur&iacute;dico aplicable</p>
    </li>
    <li>
        <p style="text-align: justify;background: transparent;margin-top: 0.21cm;margin-bottom: 0.21cm;line-height: 0.42cm;">Las presentes Condiciones de Uso</p>
    </li>
    <li>
        <p style="text-align: justify;background: transparent;margin-top: 0.21cm;margin-bottom: 0.21cm;line-height: 0.42cm;">Las cláusulas establecidas entre el Propietario e Inmozon en el contrato firmado entre las partes&nbsp;</p>
    </li>
    <li>
        <p style="text-align: justify;background: transparent;margin-top: 0.21cm;margin-bottom: 0.21cm;line-height: 0.42cm;">Las buenas costumbres</p>
    </li>
    <li>
        <p style="text-align: justify;background: transparent;margin-top: 0.21cm;margin-bottom: 0.21cm;line-height: 0.42cm;">El orden p&uacute;blico</p>
    </li>
</ol>
<p style="text-align: justify;background: transparent;margin-top: 0.21cm;margin-bottom: 0.21cm;line-height: 0.42cm;"><br><br></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Asimismo, el Usuario se compromete expresamente a no destruir, alterar, inutilizar o, de cualquier otra forma, da&ntilde;ar los datos, programas o documentos electr&oacute;nicos y dem&aacute;s que se encuentren en el Portal de www.inmozon.com</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">El Usuario se compromete a no transmitir, introducir, difundir y poner a disposici&oacute;n de terceros cualquier tipo de material e informaci&oacute;n (programas, virus, macros, applets, controles ActiveX, datos, contenidos, dibujos, archivos de sonido e imagen, etc.) que sean contrarios a la ley, el orden p&uacute;blico o que causen o sean susceptibles de causar cualquier tipo de alteraci&oacute;n en los sistemas inform&aacute;ticos de Inmozon o de terceros.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><strong>4.- Propiedad intelectual e industrial</strong></p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">INMOZON es titular o licenciataria de todos los derechos de propiedad intelectual e industrial incluidos en la Plataforma as&iacute; como sobre los contenidos accesibles a trav&eacute;s de la misma. Los derechos de propiedad intelectual de la Plataforma, as&iacute; como: textos, im&aacute;genes, fotograf&iacute;as, dise&ntilde;o gr&aacute;fico, estructura de navegaci&oacute;n, informaci&oacute;n y contenidos que se recogen en ella son titularidad de INMOZON, a quien corresponde el ejercicio exclusivo de los derechos de explotaci&oacute;n de los mismos en cualquier forma y, en especial, los derechos de reproducci&oacute;n, distribuci&oacute;n, comunicaci&oacute;n p&uacute;blica y transformaci&oacute;n, de conformidad con la legislaci&oacute;n espa&ntilde;ola de derechos de propiedad intelectual e industrial. La autorizaci&oacute;n a LA PROPIEDAD para el acceso a la plataforma no supone renuncia, transmisi&oacute;n, licencia o cesi&oacute;n total ni parcial sobre derechos de propiedad intelectual o industrial por parte de INMOZON.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">No est&aacute; permitido suprimir, eludir o manipular de ning&uacute;n modo los contenidos de la Plataforma de INMOZON</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Asimismo, est&aacute; prohibido modificar, copiar, reutilizar, explotar, reproducir, comunicar p&uacute;blicamente, hacer segundas o posteriores publicaciones, cargar archivos, enviar por correo, transmitir, usar, tratar o distribuir de cualquier forma la totalidad o parte de los contenidos incluidos en la Plataforma para prop&oacute;sitos p&uacute;blicos o comerciales, si no se cuenta con la autorizaci&oacute;n expresa y por escrito de INMOZON o, en su caso, del titular de los derechos a que corresponda.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">La propiedad que proceda a compartir cualquier tipo de contenido a trav&eacute;s de la plataforma, asegura que ostenta los derechos necesarios para hacerlo, quedando exento Inmozon de cualquier responsabilidad sobre el contenido y legalidad de la informaci&oacute;n ofrecida. La facilitaci&oacute;n de contenidos por parte de la propiedad a trav&eacute;s de la plataforma supondr&aacute; la cesi&oacute;n a Inmozon, con car&aacute;cter gratuito, y con la m&aacute;xima amplitud permitida por la legislaci&oacute;n vigente, de los derechos de explotaci&oacute;n de propiedad intelectual o industrial derivados de tales contenidos.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">La propiedad se obliga a usar los contenidos de forma diligente, correcta y l&iacute;cita y, en particular, se compromete a abstenerse de suprimir, eludir o manipular el &quot;copyright&quot; y dem&aacute;s datos identificativos de los derechos de Inmozon o de sus titulares incorporados a los contenidos, as&iacute; como a los dispositivos t&eacute;cnicos de protecci&oacute;n o cualesquiera mecanismos de informaci&oacute;n que pudieren incluirse en los contenidos. Asimismo, el usuario se abstendr&aacute; de emplear los contenidos y, en particular, la informaci&oacute;n de cualquier clase obtenida a trav&eacute;s del Sitio Web para remitir publicidad, comunicaciones con fines comerciales, mensajes no solicitados dirigidos a una pluralidad de personas con independencia de su finalidad, as&iacute; como a abstenerse de comercializar o divulgar de cualquier modo dicha informaci&oacute;n</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;">Inmozon informa que no concede licencia o autorizaci&oacute;n impl&iacute;cita alguna sobre los derechos de propiedad intelectual y/o industrial o sobre cualquier otro derecho o propiedad relacionada, directa o indirectamente, con los contenidos incluidos en la web.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><strong>5.- Derecho de limitar o poner fin al servicio de Inmozon</strong></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Inmozon se reserva el derecho, ejercitable en cualquier momento y de modo discrecional a rechazar cualquier anuncio. Inmozon tambi&eacute;n se reserva el derecho de eliminar cualquier anuncio del Portal sin necesidad de avisar previamente a los usuarios.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Inmozon puede denegar o poner fin a su servicio y adoptar medidas t&eacute;cnicas y legales para mantener a los usuarios alejados del Portal si creemos que est&aacute;n creando problemas o actuando de forma contraria al esp&iacute;ritu o la forma de nuestras normas y condiciones de uso. Sin embargo, decidamos o no retirar el acceso al sitio web de un usuario, no aceptamos ninguna responsabilidad por el uso no autorizado o ilegal del sitio web por los usuarios, tal y como se describe en los p&aacute;rrafos anteriores.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><strong>6.- Varios</strong></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">1. Modificaciones en el Servicio y Condiciones de Uso</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Inmozon se reserva el derecho a realizar cambios en el Portal, pudiendo modificar, suprimir e incluir, unilateralmente y sin previo aviso, nuevos contenidos as&iacute; como la forma en que estos aparezcan presentados y localizados.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Asimismo, Inmozon se reserva el derecho a realizar cambios las presentes Condiciones de Uso en cualquier momento. El usuario quedar&aacute; sujeto a las nuevas Condiciones de Uso que hayan sido publicadas en el momento en que acceda o utilice los servicios de Inmozon.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Si alguna de las presentes condiciones resulta invalidada, nula o inaplicable por cualquier motivo, dicha condici&oacute;n quedar&aacute; excluida y no afectar&aacute; a la validez ni la aplicabilidad del resto de condiciones.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">2. Precios de los Servicios</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Los precios de los servicios ser&aacute;n establecidos en los correspondientes contratos firmados entre las partes intervinientes en el portal.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><strong>7.- Duraci&oacute;n y terminaci&oacute;n</strong></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">La prestaci&oacute;n de los servicios y/o contenidos del Portal tiene una duraci&oacute;n establecida en los contratos firmados entre las partes.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Sin perjuicio de lo anterior, y adem&aacute;s de por las causas establecidas legalmente, Inmozon est&aacute; facultada para dar por terminada, suspender o interrumpir unilateralmente, en cualquier momento y sin necesidad de preaviso, la prestaci&oacute;n del servicio y del Portal y/o cualquiera de los servicios.</p>
<p style="text-align: justify;background: transparent;margin-bottom: 0.28cm;line-height: 0.42cm;"><strong>8.-&nbsp;</strong><strong>Tratamiento de datos de car&aacute;cter personal&nbsp;</strong></p>
<p style="text-align: justify;background: transparent;margin-bottom: 0cm;line-height: 0.42cm;">En cumplimiento de lo previsto por el Reglamento (UE) 2016/679, del Parlamento Europeo y del Consejo, de 27 de abril de 2016 y la Ley Org&aacute;nica 3/2018 de 5 de diciembre (LOPDGDD), relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales (Reglamento Europeo de Protecci&oacute;n de Datos) le informamos que los datos personales que puedan constar en este documento se encuentran incorporados en un fichero propiedad de INMOAREA PARTNERS S.L con la finalidad de gestionar nuestra relaci&oacute;n contractual y poder informarle de nuestros servicios. Si desea ejercitar sus derechos de acceso, oposici&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n, supresi&oacute;n, limitaci&oacute;n y portabilidad lo podr&aacute; hacer dirigi&eacute;ndose por escrito en la siguiente direcci&oacute;n de correo electr&oacute;nico: info@inmozon.com</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><strong>9.- Jurisdicci&oacute;n</strong></p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">La ley aplicable en caso de disputa o conflicto de interpretaci&oacute;n de los t&eacute;rminos que conforman estas Condiciones de Uso, as&iacute; como cualquier cuesti&oacute;n relacionada con los servicios del Portal, ser&aacute; la ley espa&ntilde;ola.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;">Para la resoluci&oacute;n de cualquier controversia que pudiera surgir con ocasi&oacute;n del uso del Portal y sus servicios, las partes acuerdan someterse a la jurisdicci&oacute;n de los Juzgados y Tribunales de la ciudad de Alicante (Espa&ntilde;a), y sus superiores jer&aacute;rquicos, con expresa renuncia a otros fueros si lo tuvieren y fueran diferentes de los rese&ntilde;ados.</p>
<p style="text-align: justify;background: transparent;margin-top: 0.49cm;margin-bottom: 0.49cm;line-height: 0.42cm;"><br><br></p>
</div>
